<footer>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav w-100 d-flex justify-content-evenly flex-wrap">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                    <a class="nav-link" href="/register">Registrar</a>
                    <a class="nav-link" href="#">Sobre a Empresa</a>
                    <a class="nav-link">Trabalhe Conosco</a>
                </div>
            </div>
        </div>
    </nav>
</footer>