<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" sizes="16x16"  href="/data/icons/favicon.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <title>Blogs</title>

    <?php
    //Buscar Caminho URL Atual
    $currentUrl = $_SERVER['REQUEST_URI'];
    $path = parse_url($currentUrl, PHP_URL_PATH);
    $parts = explode('/', $path);

    if (count($parts) <= 2 && $parts[1] == '') {
        $activePage = 'index';
    } else {
        $activePage = $parts[1];
    }
    ?>

    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <?php
    $cssLinkPage = '<link rel="stylesheet" type="text/css" href="/css/'.$activePage.'.css">';
    if (file_exists('css/'.$activePage.'.css')) {
        echo $cssLinkPage;
    }
    ?>

    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="/libs/alertify/css/alertify.min.css">
    <link rel="stylesheet" type="text/css" href="/libs/alertify/css/themes/default.min.css">
    <link rel="stylesheet" type="text/css" href="/libs/lightbox/dist/css/lightbox.min.css">
    <link rel="stylesheet" type="text/css" href="/libs/cropperjs/dist/cropper.min.css">


</head>


<body>
    <?= $this->content(); ?>

    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="/libs/alertify/alertify.min.js"></script>
    <script src="/libs/lightbox/dist/js/lightbox.min.js"></script>
    <script src="/libs/lightbox/dist/js/lightbox-plus-jquery.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="/libs/cropperjs/dist/cropper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/locale/pt-br.min.js"></script>
    <script src="/js/utils.js"></script>
    <script src="/js/navbar.js"></script>
    <?php
    $scriptPage = '<script src="/js/'.$activePage.'.js"></script>';
    if (file_exists('js/'.$activePage.'.js')) {
        echo $scriptPage;
    }
    ?>

</body>

</html>